### ISSUE TITLE
Add fault-tolerant way of getting swap status

### ISSUE THREAD

**Issue by ok300** [breez/breez-sdk-liquid#109]
In this project, we're always fetching it from Boltz with `BoltzApiClient::swap_status`. This can leave us exposed to issues like https://github.com/BoltzExchange/boltz-backend/issues/537 , causing us to fail to fetch the swap status and therefore fail to complete the swap (#104).

In contrast, in Breez SDK we're calculating the swap status ourselves: https://github.com/breez/breez-sdk/blob/2c1bcfced2cf36fa9f7baee5de8bbb1c81838c1e/libs/sdk-core/src/models.rs#L1450

We should fallbacks and redundancies, to make us resilient to the error above.

A few possible ideas:
- instead of `BoltzApiClient::swap_status` we calculate the status ourselves
- we first try `BoltzApiClient::swap_status`, then if it fails, we fallback to our own calculation
- we first try the v2 Boltz API (fastest), then if it fails the v1 `BoltzApiClient::swap_status`, then our calculation

**Comment by roeierez** [comment]
Currently we always validate boltz status, closing this issue.

**Comment by ok300** [comment]
This issue was not about validation, but making us resilient to single points of failures.

The issue [linked above](https://github.com/BoltzExchange/boltz-backend/issues/537)  caused us to not get any new mainnet swap status updates for a few days. It was caused by a misconfiguration of the Boltz API mainnet endpoint.

**Comment by roeierez** [comment]
If the swapper API is misconfigured it could cause many other issues such as no cooperative refunds and even not able to complete a swap succesfully.
The only way to me robust here is to ensure user not loosing funds, e.g the sdk will refund in case these cases which is what we are doing ATM.
