### ISSUE TITLE
Receive: claim address re-use if receiving multiple times in rapid succession

### ISSUE THREAD

**Issue by ok300** [breez/breez-sdk-liquid#195]
If receiving several times in parallel, such all claim txs are in the mempool at the same time, all Receives will re-use the same claim address.

How to reproduce:
- SDK: initiate a Receive
- sender wallet: pay the invoice
- SDK: immediately initiate a new Receive and repeat
- stop when the next Liquid block is mined[^1]
- look for the claim txid in the log, open it in an explorer and navigate to the destination address (the claim address)

[^1]: https://liquid.network/testnet

**Comment by roeierez** [comment]
@ok300  What is the problem we have here if we claim to the same address?

**Comment by ok300** [comment]
Privacy issue (address re-use), where these Receive swaps can be linked to the same user.

**Comment by dangeross** [comment]
Closed by #531
