### ISSUE TITLE
Add support for `drain` (send all L-BTC)

### ISSUE THREAD

**Issue by ok300** [breez/breez-sdk-liquid#211]

**Comment by roeierez** [comment]
We probably should add max_payable amount to the send chain swap limits.
Currently we only show the limit of the swapper, we should add the limit based on the balance and fees so users can get the max amount they can send to a btc address.

**Comment by ok300** [comment]
My understanding of "`drain` (send all L-BTC)" is "send all L-BTC to a L-BTC address" (identical to `drain` in LWK).

My understanding of the new `max_payable` in `fetch_onchain_limits` is "max L-BTC amount we can send to a BTC address" (via chain swap).

@roeierez @erdemyerebasmaz Does this mean there will be no `drain` ("send all LBTC to LBTC addr"), but it will be replaced with the 2nd feature above? Asking because of the 50k sat artificial limit in the chain swap, which doesn't exist in the initial `drain`. This "send all available funds" cannot be used for balances below 50k.

**Comment by roeierez** [comment]
Yes, we only want to support sending all to a btc address (same as the greenlight sdk).
