### ISSUE TITLE
Pause events during first `sync`

### ISSUE THREAD

**Issue by ok300** [breez/breez-sdk-liquid#300]
The first call to `sync` on a new setup with some pre-existing onchain history will cause a wave of `LiquidSdkEvent::PaymentSucceed` events.

This is because the newly discovered items in the wallet's history are indistinguishable from actual new Send / Receive direct payments.

One solution is to pause events for the duration of the first `sync`, and particularly  `sync_payments_with_chain_data`.

**Comment by dangeross** [comment]
This seems to happen for pending payments also, on each sync the pending event is emitted
