### ISSUE TITLE
Display expiration time on payment details dialog for pending payments

### ISSUE THREAD

**Issue by erdemyerebasmaz** [breez/breez-sdk-liquid#416]
Depends on:
- https://github.com/breez/breez-sdk-liquid/issues/415

**Comment by roeierez** [comment]
This seems related to the UI part in misty breez.

**Comment by erdemyerebasmaz** [comment]
> This seems related to the UI part in misty breez.

True, this issue was opened here by mistake. 

Creating it on misty-breez repository.
