### ISSUE TITLE
`SdkEvent::PaymentSucceeded` event is emitted for each payment after restoring

### ISSUE THREAD

**Issue by erdemyerebasmaz** [breez/breez-sdk-liquid#422]
SDK is firing `SdkEvent::PaymentSucceeded` event for each payment when restoring a wallet.

This is becoming a bit of a burden on binding event handlers when restoring wallets with big payment histories.

Would it be possible to differentiate reconnect & restore flows and silence them when restoring?

**Comment by ok300** [comment]
Looks like a duplicate of #300

**Comment by erdemyerebasmaz** [comment]
Closing in favor of #300
