### ISSUE TITLE
Inconsistent payment event emission for Liquid SDK wallet transfers

### ISSUE THREAD

**Issue by Laderlappen** [breez/breez-sdk-liquid#458]
Currently, there's an inconsistency in payment event emission between different types of transactions in the Breez Liquid SDK:

1. When paying a lightning invoice from a non-Liquid Breez wallet to a Liquid Breez wallet:
   - `PAYMENT_WAITING_CONFIRMATION` and `PAYMENT_PENDING` events are emitted.

2. When transferring between two Liquid SDK wallets:
   - These events are not emitted.

Expected behavior:
For consistency and improved user experience, we should emit `PAYMENT_WAITING_CONFIRMATION` and `PAYMENT_PENDING` events for all types of transactions, including Liquid transfers and lightning payments between SDK wallets.

Benefits:
- Consistent behavior across different transaction types
- Faster feedback to users about incoming pending/unconfirmed payments
- Improved ability for developers to implement responsive UIs for all transaction types

Additional context:
This improvement would allow for a more uniform approach to handling incoming payments in applications using the Breez SDK, regardless of the payment method or wallet type involved.

**Comment by roeierez** [comment]
Thanks @Laderlappen for this.
I think that makes sense just want to clarify some things:

Sending to liquid address
* We will emit PAYMENT_PENDING immediately before broadcasting
* We will emit PAYMENT_WAITING_CONFIRMATION after broadcasting has completed and tx is in mempool
* We will emit PAYMENT_SUCCEEDED after transaction has been confirmed (this should already work atm)

Receiving to liquid address
* We will emit PAYMENT_WAITING_CONFIRMATION as soon as we detect an incoming tx in mempool
* We will emit PAYMENT_SUCCEEDED after transaction has been confirmed (this should already work atm)

Please notice that for receiving we won't emit the PAYMENT_PENDING event as it doesn't differ from the PAYMENT_WAITING_CONFIRMATION in this case. The state of the payment will be still PENDING

Let me know if that is aligned with your thoughts.

**Comment by Laderlappen** [comment]
Yes @roeierez that is right, thank you for clarifying.
