### ISSUE TITLE
`list_payments`: Pending payments break reverse chronological order

### ISSUE THREAD

**Issue by erdemyerebasmaz** [breez/breez-sdk-liquid#540]
In the `list_payments` function, pending payments break the expected reverse chronological order of transactions. This behavior results in an inconsistent ordering, where completed payments are listed by most recent first, but pending payments appear out of sequence at the end of the list.

**Comment by dangeross** [comment]
Payments are currently ordered by tx timestamp or swap creation timestamp `COALESCE(tx.timestamp, swap.created_at) DESC`, so yes completed payments bubble up. It does break the "chronological" ordering if you only count the creation timestamp, so I'll change reverse the ordering to first order by swap creation timestamp. The payment timestamp should still show the tx time if set.
